/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author osmakevinn
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents(); // Esto lo dejas tal cual
        setTitle("Gestión Barberia");

        // --- MEJORAS VISUALES PREMIUM ---
        btnInicio.setContentAreaFilled(false);
        btnBarberos.setContentAreaFilled(false);
        btnClientes.setContentAreaFilled(false);
        btnCitas.setContentAreaFilled(false);
        btnServicios.setContentAreaFilled(false);
        btnConfiguracion.setContentAreaFilled(false);
        btnSalir.setContentAreaFilled(false);

        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBarberos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCitas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnServicios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        
        // Aplicamos el formato plano
        configurarEstiloMenu(btnInicio);
        configurarEstiloMenu(btnBarberos);
        configurarEstiloMenu(btnClientes);
        configurarEstiloMenu(btnCitas);
        configurarEstiloMenu(btnServicios);
        configurarEstiloMenu(btnConfiguracion);
        configurarEstiloMenu(btnSalir);

        mostrarPanel(new PnlInicio());
        
        // Dejamos marcado solo el inicio al arrancar
        btnInicio.setSelected(true);
    }
        
    private void mostrarPanel(JPanel p){
            p.setSize(content.getWidth(), content.getHeight());
            p.setLocation(0, 0);
        
            content.removeAll();
            content.add(p, java.awt.BorderLayout.CENTER);
            content.revalidate();
            content.repaint();    
    }
    
    
    private void configurarEstiloMenu(javax.swing.JButton boton) {

        java.awt.Color colorNormal = new java.awt.Color(48, 47, 47);
        java.awt.Color colorHover = new java.awt.Color(70, 70, 70);
        java.awt.Color colorSeleccionado = new java.awt.Color(90, 90, 90);

        boton.setFocusPainted(false);
        boton.setBorderPainted(false);
        boton.setContentAreaFilled(true);
        boton.setOpaque(true);

        boton.setBackground(colorNormal);
        boton.setForeground(java.awt.Color.WHITE);

        // EFECTO HOVER
        boton.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {

                if (!boton.isSelected()) {
                    boton.setBackground(colorHover);
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {

                if (!boton.isSelected()) {
                    boton.setBackground(colorNormal);
                }
            }
        });

        // EFECTO SELECCIONADO
        boton.addActionListener(e -> {

            resetearFormatoBotones();

            btnInicio.setBackground(colorNormal);
            btnBarberos.setBackground(colorNormal);
            btnClientes.setBackground(colorNormal);
            btnCitas.setBackground(colorNormal);
            btnServicios.setBackground(colorNormal);
            btnConfiguracion.setBackground(colorNormal);
            btnSalir.setBackground(colorNormal);

            boton.setSelected(true);
            boton.setBackground(colorSeleccionado);
        });
    }

    private void resetearFormatoBotones() {

        btnInicio.setSelected(false);
        btnBarberos.setSelected(false);
        btnClientes.setSelected(false);
        btnCitas.setSelected(false);
        btnServicios.setSelected(false);
        btnConfiguracion.setSelected(false);
        btnSalir.setSelected(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnBarberos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(48, 47, 47));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barber-pole.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("MENU");

        btnInicio.setBackground(new java.awt.Color(48, 47, 47));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        btnInicio.setText("   Inicio");
        btnInicio.setSelected(true);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnBarberos.setBackground(new java.awt.Color(48, 47, 47));
        btnBarberos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBarberos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hairdresser.png"))); // NOI18N
        btnBarberos.setText("   Gestión Barberos");
        btnBarberos.setSelected(true);
        btnBarberos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarberosActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(48, 47, 47));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/client.png"))); // NOI18N
        btnClientes.setText("   Clientes");
        btnClientes.setSelected(true);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnCitas.setBackground(new java.awt.Color(48, 47, 47));
        btnCitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/schedule.png"))); // NOI18N
        btnCitas.setText("   Citas");
        btnCitas.setSelected(true);
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        btnServicios.setBackground(new java.awt.Color(48, 47, 47));
        btnServicios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barber.png"))); // NOI18N
        btnServicios.setText("   Servicios");
        btnServicios.setSelected(true);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });

        btnConfiguracion.setBackground(new java.awt.Color(48, 47, 47));
        btnConfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cogwheel.png"))); // NOI18N
        btnConfiguracion.setText("   Configuración");
        btnConfiguracion.setSelected(true);
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(48, 47, 47));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        btnSalir.setText("   Salir");
        btnSalir.setSelected(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblLogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInicio)
                            .addComponent(btnBarberos)
                            .addComponent(btnClientes)
                            .addComponent(btnCitas)
                            .addComponent(btnServicios)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConfiguracion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnInicio)
                .addGap(18, 18, 18)
                .addComponent(btnBarberos)
                .addGap(18, 18, 18)
                .addComponent(btnClientes)
                .addGap(18, 18, 18)
                .addComponent(btnCitas)
                .addGap(18, 18, 18)
                .addComponent(btnServicios)
                .addGap(18, 18, 18)
                .addComponent(btnConfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(25, 25, 25));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        mostrarPanel(new PnlClientes());
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        mostrarPanel(new PnlCitas());
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        mostrarPanel(new PnlServicios());
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
       mostrarPanel(new PnlConfiguracion());
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnBarberosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarberosActionPerformed
        resetearFormatoBotones(); 
        mostrarPanel(new PnlBarberos());
    }//GEN-LAST:event_btnBarberosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro de que desea cerrar la sesión?", 
            "Confirmar Salida", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0); // Cierra completamente la aplicación
    }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        resetearFormatoBotones(); // Resetea todos a transparentes
        mostrarPanel(new PnlInicio()); // Carga tu panel de inicio
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    try {

        com.formdev.flatlaf.FlatDarkLaf.setup();

    } catch(Exception ex) {

        System.err.println("Error al cargar FlatLaf");

    }

    java.awt.EventQueue.invokeLater(() -> {
        new FrmPrincipal().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarberos;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnServicios;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
