
package vista;

import javax.swing.JOptionPane;
import com.toedter.calendar.JTextFieldDateEditor;
import java.util.Date;
import Metodos.Mcitas;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author osmakevinn
 */
public class PnlCitas extends javax.swing.JPanel {

        private void configurarFecha() {
    // Formato correcto para la fecha
    jDateChooser1.setDateFormatString("yyyy-MM-dd");

    // Poner la fecha actual por defecto
    jDateChooser1.setDate(new Date());

    
    JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooser1.getDateEditor();
    editor.setEditable(false);
}
    private void cargarDatosIniciales() {
    mCitas.cargarClientes(cbCitCliente);
    mCitas.cargarBarberos(cbCitBarbero);
    mCitas.cargarServicios(cbCitServicio);
    mCitas.llenarTabla(jTable1);
}
     private Mcitas mCitas = new Mcitas();
     private int idCitaSeleccionada = -1;
   
    public PnlCitas() {
        initComponents();
        configurarFecha();
        cargarDatosIniciales();
       
    }
    
    private void seleccionarComboPorId(javax.swing.JComboBox<String> combo, int id) {
    for (int i = 0; i < combo.getItemCount(); i++) {
        String item = combo.getItemAt(i);

        if (item != null && item.startsWith(id + " - ")) {
            combo.setSelectedIndex(i);
            return;
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbCitCliente = new javax.swing.JComboBox<>();
        cbCitBarbero = new javax.swing.JComboBox<>();
        cbCitServicio = new javax.swing.JComboBox<>();
        cbCitEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTIÓN CITAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel1.setOpaque(false);

        cbCitBarbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCitBarberoActionPerformed(evt);
            }
        });

        cbCitEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Completada", "Cancelada" }));
        cbCitEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCitEstadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cliente:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Barbero:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Servicios:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Estado:");

        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Fecha:");

        btnGuardar.setBackground(new java.awt.Color(0, 153, 51));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(20, 120, 224));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(195, 61, 61));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Barbero", "Servicio", "Fecha", "Hora", "Estado"
            }
        ));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Hora:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel7))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCitCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCitBarbero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCitServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbCitEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbCitEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCitBarbero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCitServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCitEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCitEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCitEstadoActionPerformed

    private void cbCitBarberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCitBarberoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCitBarberoActionPerformed
private void limpiarFormularioCita() {
        idCitaSeleccionada = -1;
    cbCitCliente.setSelectedIndex(0);
    cbCitBarbero.setSelectedIndex(0);
    cbCitServicio.setSelectedIndex(0);
    cbCitEstado.setSelectedIndex(0);
    jDateChooser1.setDate(new Date());
    jTextField1.setText("");
    jTable1.clearSelection();
}
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      int idCliente = obtenerIdCombo(cbCitCliente);
    int idBarbero = obtenerIdCombo(cbCitBarbero);
    int idServicio = obtenerIdCombo(cbCitServicio);

    Date fechaDate = jDateChooser1.getDate();
    String hora = jTextField1.getText().trim();
    String estado = cbCitEstado.getSelectedItem().toString();

    if (idCliente == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un cliente");
        return;
    }

    if (idBarbero == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un barbero");
        return;
    }

    if (idServicio == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un servicio");
        return;
    }

    if (fechaDate == null) {
        JOptionPane.showMessageDialog(this, "Seleccione una fecha válida");
        return;
    }

    if (hora.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese la hora de la cita");
        return;
    }

    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    String fecha = formato.format(fechaDate);

    mCitas.registrarCita(idCliente, idBarbero, idServicio, fecha, hora, estado);

    JOptionPane.showMessageDialog(this, "Cita registrada correctamente");

    mCitas.llenarTabla(jTable1);
    limpiarFormularioCita();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (idCitaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una cita de la tabla para actualizar");
        return;
    }

    int idCliente = obtenerIdCombo(cbCitCliente);
    int idBarbero = obtenerIdCombo(cbCitBarbero);
    int idServicio = obtenerIdCombo(cbCitServicio);

    Date fechaDate = jDateChooser1.getDate();
    String hora = jTextField1.getText().trim();
    String estado = cbCitEstado.getSelectedItem().toString();

    if (idCliente == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un cliente");
        return;
    }

    if (idBarbero == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un barbero");
        return;
    }

    if (idServicio == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un servicio");
        return;
    }

    if (fechaDate == null) {
        JOptionPane.showMessageDialog(this, "Seleccione una fecha válida");
        return;
    }

    if (hora.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese la hora de la cita");
        return;
    }

    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    String fecha = formato.format(fechaDate);

    mCitas.actualizarCita(
            idCitaSeleccionada,
            idCliente,
            idBarbero,
            idServicio,
            fecha,
            hora,
            estado
    );

    JOptionPane.showMessageDialog(this, "Cita actualizada correctamente");

    mCitas.llenarTabla(jTable1);
    limpiarFormularioCita();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      if (idCitaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una cita de la tabla para eliminar");
        return;
    }

    int respuesta = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de eliminar esta cita?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (respuesta == JOptionPane.YES_OPTION) {
        mCitas.eliminarCita(idCitaSeleccionada);

        JOptionPane.showMessageDialog(this, "Cita eliminada correctamente");

        mCitas.llenarTabla(jTable1);
        limpiarFormularioCita();
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
   
   limpiarFormularioCita();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 int fila = jTable1.getSelectedRow();

    if (fila == -1) {
        return;
    }
      idCitaSeleccionada = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());

    String cliente = jTable1.getValueAt(fila, 1).toString();
    String barbero = jTable1.getValueAt(fila, 2).toString();
    String servicio = jTable1.getValueAt(fila, 3).toString();
    String fechaTexto = jTable1.getValueAt(fila, 4).toString();
    String hora = jTable1.getValueAt(fila, 5).toString();
    String estado = jTable1.getValueAt(fila, 6).toString();

    // Como la tabla muestra nombres, buscamos en los combos por texto
    seleccionarComboPorTexto(cbCitCliente, cliente);
    seleccionarComboPorTexto(cbCitBarbero, barbero);
    seleccionarComboPorTexto(cbCitServicio, servicio);

    try {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha = formato.parse(fechaTexto);
        jDateChooser1.setDate(fecha);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar la fecha de la cita");
    }

    jTextField1.setText(hora);
    cbCitEstado.setSelectedItem(estado);
    
    }//GEN-LAST:event_jTable1MouseClicked

private void seleccionarComboPorTexto(javax.swing.JComboBox<String> combo, String texto) {
    for (int i = 0; i < combo.getItemCount(); i++) {
        String item = combo.getItemAt(i);

        if (item != null && item.contains(" - " + texto)) {
            combo.setSelectedIndex(i);
            return;
        }
    }
}

    private int obtenerIdCombo(javax.swing.JComboBox<String> combo) {
    String item = (String) combo.getSelectedItem();

    if (item == null || item.equals("Seleccione...")) {
        return -1;
    }

    String[] partes = item.split(" - ");
    return Integer.parseInt(partes[0]);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbCitBarbero;
    private javax.swing.JComboBox<String> cbCitCliente;
    private javax.swing.JComboBox<String> cbCitEstado;
    private javax.swing.JComboBox<String> cbCitServicio;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

