/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import Metodos.MetodosBarberos;

/**
 *
 * @author osmakevinn
 */
public class PnlInicio extends javax.swing.JPanel {
    
    MetodosBarberos md = new MetodosBarberos();   
    
    
    public PnlInicio() {
        initComponents();
        estilos();

        try {
            lblTotalClientes.setText(String.valueOf(md.totalClientes()));
            lblTotalBarberos.setText(String.valueOf(md.totalBarberos()));
            lblTotalCitas.setText(String.valueOf(md.totalCitasHoy()));
            lblTotalServicios.setText(String.valueOf(md.totalServicios()));

            cargarTablaProximasCitas();
        } catch (Exception e) {
            System.out.println("Nota: Implementar métodos en MetodosBarberos: " + e.getMessage());
        }
    }
    
    private void estilos() {

        // ===== ESTILO TARJETAS =====
        pnlClientes.putClientProperty("FlatLaf.style", "arc:20");
        pnlCitas.putClientProperty("FlatLaf.style", "arc:20");
        pnlBarberos.putClientProperty("FlatLaf.style", "arc:20");
        pnlServicios.putClientProperty("FlatLaf.style", "arc:20");

        // ===== COLORES =====
        pnlClientes.setBackground(new java.awt.Color(45, 45, 45));
        pnlCitas.setBackground(new java.awt.Color(45, 45, 45));
        pnlBarberos.setBackground(new java.awt.Color(45, 45, 45));
        pnlServicios.setBackground(new java.awt.Color(45, 45, 45));

    }
    
    private void cargarTablaProximasCitas() {
        // Solo se ejecutará si ya creaste la tabla 'tblProximasCitas' en el diseño
        if (tblProximasCitas != null) {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblProximasCitas.getModel();
            modelo.setRowCount(0);

            try {
                java.util.List<Object[]> lista = md.listarProximasCitas();
                if (lista != null) {
                    for (Object[] fila : lista) {
                        modelo.addRow(fila);
                    }
                }
            } catch (Exception e) {
                System.out.println("Error al cargar filas de citas: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlClientes = new javax.swing.JPanel();
        lblTituloClientes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalClientes = new javax.swing.JLabel();
        pnlCitas = new javax.swing.JPanel();
        lblTituloCitas = new javax.swing.JLabel();
        lblTotalCitas = new javax.swing.JLabel();
        pnlBarberos = new javax.swing.JPanel();
        lblTituloBarberos = new javax.swing.JLabel();
        lblTotalBarberos = new javax.swing.JLabel();
        pnlServicios = new javax.swing.JPanel();
        lblTituloServicios = new javax.swing.JLabel();
        lblTotalServicios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProximasCitas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inicio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel5.setText("Bienvenido, ");

        pnlClientes.setBackground(new java.awt.Color(45, 45, 45));
        pnlClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlClientes.setOpaque(false);
        pnlClientes.setPreferredSize(new java.awt.Dimension(200, 150));

        lblTituloClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloClientes.setText("Clientes");

        lblTotalClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalClientes.setText("0");

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblTituloClientes))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblTotalClientes)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloClientes)
                .addGap(18, 18, 18)
                .addComponent(lblTotalClientes)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlCitas.setBackground(new java.awt.Color(45, 45, 45));
        pnlCitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlCitas.setOpaque(false);
        pnlCitas.setPreferredSize(new java.awt.Dimension(200, 150));

        lblTituloCitas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCitas.setText("Citas hoy");

        lblTotalCitas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalCitas.setText("0");

        javax.swing.GroupLayout pnlCitasLayout = new javax.swing.GroupLayout(pnlCitas);
        pnlCitas.setLayout(pnlCitasLayout);
        pnlCitasLayout.setHorizontalGroup(
            pnlCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCitasLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblTituloCitas)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(pnlCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCitasLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(lblTotalCitas)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
        pnlCitasLayout.setVerticalGroup(
            pnlCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCitas)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(pnlCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCitasLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(lblTotalCitas)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        pnlBarberos.setBackground(new java.awt.Color(45, 45, 45));
        pnlBarberos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBarberos.setOpaque(false);
        pnlBarberos.setPreferredSize(new java.awt.Dimension(200, 150));

        lblTituloBarberos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloBarberos.setText("Barberos");

        lblTotalBarberos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalBarberos.setText("0");

        javax.swing.GroupLayout pnlBarberosLayout = new javax.swing.GroupLayout(pnlBarberos);
        pnlBarberos.setLayout(pnlBarberosLayout);
        pnlBarberosLayout.setHorizontalGroup(
            pnlBarberosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarberosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTituloBarberos)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(pnlBarberosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBarberosLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(lblTotalBarberos)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
        pnlBarberosLayout.setVerticalGroup(
            pnlBarberosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarberosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloBarberos)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(pnlBarberosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBarberosLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(lblTotalBarberos)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        pnlServicios.setBackground(new java.awt.Color(45, 45, 45));
        pnlServicios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlServicios.setOpaque(false);
        pnlServicios.setPreferredSize(new java.awt.Dimension(200, 150));

        lblTituloServicios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloServicios.setText("Servicios");

        lblTotalServicios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalServicios.setText("0");

        javax.swing.GroupLayout pnlServiciosLayout = new javax.swing.GroupLayout(pnlServicios);
        pnlServicios.setLayout(pnlServiciosLayout);
        pnlServiciosLayout.setHorizontalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTituloServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlServiciosLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(lblTotalServicios)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
        pnlServiciosLayout.setVerticalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloServicios)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlServiciosLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(lblTotalServicios)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Próximas citas:");

        tblProximasCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Barbero", "Hora", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProximasCitas.setRowSelectionAllowed(false);
        tblProximasCitas.setShowHorizontalLines(true);
        tblProximasCitas.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tblProximasCitas);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                            .addComponent(pnlBarberos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                            .addComponent(pnlServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                            .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBarberos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTituloBarberos;
    private javax.swing.JLabel lblTituloCitas;
    private javax.swing.JLabel lblTituloClientes;
    private javax.swing.JLabel lblTituloServicios;
    private javax.swing.JLabel lblTotalBarberos;
    private javax.swing.JLabel lblTotalCitas;
    private javax.swing.JLabel lblTotalClientes;
    private javax.swing.JLabel lblTotalServicios;
    private javax.swing.JPanel pnlBarberos;
    private javax.swing.JPanel pnlCitas;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlServicios;
    private javax.swing.JTable tblProximasCitas;
    // End of variables declaration//GEN-END:variables
}
